# name: Update F1 Penalty Points

# on:
#   schedule:
    
#     - cron: '*/30 * * * *'
#   workflow_dispatch:
#     # Allow manual triggering

# jobs:
#   update-data:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3
      
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.10'
        
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pandas lxml html5lib requests beautifulsoup4
        
#     - name: Create data directory if it doesn't exist
#       run: mkdir -p data
        
#     - name: Fetch penalty points data
#       run: python fetch_penalty_points.py
        
#     - name: Commit and push if changes
#       run: |
#         git config --local user.email "github-actions@github.com"
#         git config --local user.name "GitHub Actions"
#         git add data/penalty_points.json data/penalty_points_chart.json
#         git diff --quiet && git diff --staged --quiet || (git commit -m "Update penalty points data" && git push)
